### ISSUE TITLE
Suggestion for a introductory workshop: "Intro to cloud in DFDS"

### ISSUE THREAD

**Issue by dingobar** [dfds/dojo#11]
For teams that have not until now been exposed to cloud in any meaningful way so far (laggard segment), it would be useful to get an introduction to what DFDS have facilitated thus far, and where it is going. How to be more cloud-ready developers comes in a step after this, as the most important thing on the short term for them is to be exposed to the possibilities and reach of AWS in general and our own platform (AWS, K8s, Kafka). It is possible that some of the team members don't think the cloud setup is relevant to them in any way, and that it is just "something they have going on in the build teams", and I want to challenge that.

I see these loose agenda points which should probably be refined a bit:
- The state of the self-service platform and the possibilities it brings, with a simple demo
- Roadmap of the cloud platform, and key strategic objectives in DFDS in terms of cloud adaptation
- Why cloud is "better" than on-prem in most cases (scalability, price)
- Kubernetes: What is it, and why should I run my app in k8s rather than in a data center VM
- Other infra available (Kafka cluster, logs and monitoring, other?)

The session doesn't have to be long, just enough for the team to be exposed to your world of development excellence and to hopefully spark some curiosity and excitement in the group. I suggest 1 hour.

Thoughts?

**Comment by dingobar** [comment]
I've spoken to @carlsendk about this, and agreed that we have some work to do internally before we are ready for this. Still relevant in the long run though!

**Comment by ZaradarDFDS** [comment]
Dingobar == Martin :) (just a self-reminder)

**Comment by avnes** [comment]
Closed after team discussion.
