### ISSUE TITLE
Complete workflow inside the terminal

### ISSUE THREAD

**Issue by abstrask** [dfds/dojo#22]
Primarily VIM, some tmux. Syntax high-lighting, linters, clipboard control, indention settings, directory browsing etc.

**Comment by abstrask** [comment]
I'm hoping @wcarlsen will pick this up, when the VIM project figure out what they want to do :)

**Comment by avnes** [comment]
I am killing this Issue because of:
- It's not been prioritized for about thwo years
- It's not a clear if there is a groups of users in DFDS that are actually wanting or needing this.
