### ISSUE TITLE
Include instructions for installing Crossplane CLI on Windows

### ISSUE THREAD

**Issue by abstrask** [dfds/dojo#29]
The instructions In `crossplane-sre-deep-dive` kata 1 only has instructions for installing on Linux. It would be nice with instructions for installing on Windows too.

From my own experience:

1. Download `crank.exe` from https://releases.crossplane.io/stable/
2. Save to a folder in $PATH (I suggest `C:\bin`, in line with the [Windows prereqs](https://wiki.dfds.cloud/en/playbooks/getting-started/prereqs-win#folder-for-tool-binaries) for our platform)
3. Rename file to `kubectl-crossplane.exe`

**Comment by avnes** [comment]
Documentation was updated by @rifisdfds on November 4th, 2021
