### ISSUE TITLE
Create handout for Security Guidelines

### ISSUE THREAD

**Issue by ZaradarBH** [dfds/dojo#30]
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/tab::af171735-e2bd-4cd1-b661-071cc854efbc?context=%7B%22subEntityId%22%3A%22%7B%5C%22pageId%5C%22%3A10%2C%5C%22origin%5C%22%3A2%7D%22%2C%22channelId%22%3A%2219%3Ac4f0b4ca7ff14f8f8fe23472f9efc58b%40thread.tacv2%22%7D&tenantId=73a99466-ad05-4221-9f90-e7142aa2f6c1

**Comment by avnes** [comment]
@jdsmithit I assign this to you since @ZaradarBH has moved on to greener grass.
